name: hackoverflow_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.3
  get: ^4.6.6
  http: ^1.2.1
  skeletonizer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true


  fonts:
    - family: man-r
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: man-l
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf

    - family: man-b
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf

    - family: man-sb
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf


  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
